# Generated by Django 4.0.4 on 2022-07-04 10:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('emp_id', models.IntegerField()),
                ('emp_name', models.CharField(max_length=1000)),
                ('emp_status', models.CharField(max_length=20)),
                ('emp_type', models.CharField(max_length=100)),
                ('skill_set', models.TextField()),
                ('department', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
                ('project_name', models.CharField(max_length=100)),
                ('client_name', models.CharField(blank=True, max_length=100, null=True)),
                ('previous_client', models.CharField(max_length=100)),
                ('reason_for_offboard', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('experience', models.CharField(max_length=100)),
                ('comments', models.TextField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
            ],
        ),
    ]
